pool:
  main:
    public_ip: 88.198.45.81
    volumes:
      - monero_blockchain
      - monero_wallet
      - monero_wallet_testnet
      - monero_pool_db
      - monero_mysql
      - ethereum_redis
      - ethereum_geth
      - ethereum_geth_testnet
      - ethereum_proxy_cache
      - karbo_blockchain
      - karbo_wallet
      - karbo_mysql
      - karbo_redis
      - karbo_pool_db
      - pgdata
    containers:
      postgres:
        build: 3rdparty/postgres
        volumes:
          "/var/lib/postgresql/data": pgdata
        env:
          POSTGRES_PASSWORD: "{{ vault.postgres_password }}"
          POSTGRES_USERS: '{{ vault.postgres_users|jsonify }}'
          POSTGRES_DBS: '{{ {'pool': 'pool'}|jsonify }}'
        expose:
          5432: 5432

      pool_engine:
        build: pool_engine
        env:
          POSTGRES_HOST: postgres.main.pool
          POSTGRES_PORT: 5432
          POSTGRES_DB: pool
          POSTGRES_USER: pool
          POSTGRES_PWD: "{{ vault.postgres_users.pool }}"
        expose:
          80: 81

      block_unlocker:
        build: block_unlocker
        env:
          INTERVAL: 60
          FEE: 1
          FEE_WALLET_ETH: "0x9d18c9e946062d3109d262c1a487bcfb82346a61"
          FEE_WALLET_XMR: 4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbS22Te3GPYxy5v1EPE6
          FEE_WALLET_KRB: Kbg86BNMEiFQ61gPR6Kg9i1TXAUfaNP2KNvQZovHjhGs3DEC8MehMsGPTTCXi9bKoKH98qLMHrxLC51qJZdxXJMN3c7TsjL
          POSTGRES_HOST: postgres.main.pool
          POSTGRES_PORT: 5432
          POSTGRES_DB: pool
          POSTGRES_USER: pool
          POSTGRES_PWD: "{{ vault.postgres_users.pool }}"

      pool_karbo:
        build: pool_cryptonote
        docker_file: Dockerfile.old
        env:
          COIN: krb
          BLOCK_VALIDATOR_DEPTH: 10
          SIG_DIVISOR: 1000000000000
          WALLET_ADDRESS: Kbg86BNMEiFQ61gPR6Kg9i1TXAUfaNP2KNvQZovHjhGs3DEC8MehMsGPTTCXi9bKoKH98qLMHrxLC51qJZdxXJMN3c7TsjL
          DAEMON_HOST: karbo_daemon.main.pool
          DAEMON_PORT: 32348
          POOL_ENGINE_HOST: pool_engine.main.pool
          POOL_ENGINE_PORT: 80
        expose:
          7777: 88.198.45.21:7777
          5555: 88.198.45.21:5555
          3333: 88.198.45.21:3333
          9000: 88.198.45.21:9000

      pool_monero:
        build: pool_cryptonote
        docker_file: Dockerfile.new
        env:
          COIN: xmr
          BLOCK_VALIDATOR_DEPTH: 60
          SIG_DIVISOR: 1000000000000
          WALLET_ADDRESS: 9tYqTMPuN8KD4iG29oR3m8fvHF7XFX5q1VB2b8zBNpQxSBosvwdF3yQMToG42pbGXjb8jzKwX8PpxJLViesxeZTcShySFep
          DAEMON_HOST: testnet.xmrchain.net
          DAEMON_PORT: 28081
          POOL_ENGINE_HOST: pool_engine.main.pool
          POOL_ENGINE_PORT: 80
        expose:
          7777: 88.198.45.81:7779

#      pool_ethereum:
#        build: pool_ethereum
#        env:
#          COIN: eth
#          SIG_DIVISOR: 1000000000000000000
#          TESTNET: "false"
#          VALIDATOR_DEPTH: 120
#          PROXY_DIFFICULTY: 2000000000
#          GETH_URL: http://ethereum_geth.main.pool:8545
#          ENGINE_URL: http://pool_engine.main.pool
#        expose:
#          8080: 88.198.45.19:8080
#          8008: 88.198.45.19:8008
#          8888: 88.198.45.19:8888

      proxy_ethereum1:
        build: proxy_ethereum
        expose:
          80: 88.198.45.19:8009
        volumes:
          "/mnt": ethereum_proxy_cache
        env:
          CACHE_PATH: /mnt
          COIN: eth
          SIG_DIVISOR: 1000000000000000000
          POOL_HOST: eu1.ethermine.org
          POOL_PORT: 4444
          GETH_URL: http://ethereum_geth.main.pool:8545
          WALLET: "0x9d18c9e946062d3109d262c1a487bcfb82346a61"
          ENGINE_URL: http://pool_engine.main.pool

      api:
        build: api
        env:
          POSTGRES_HOST: postgres.main.pool
          POSTGRES_PORT: 5432
          POSTGRES_DB: pool
          POSTGRES_USER: pool
          POSTGRES_PWD: "{{ vault.postgres_users.pool }}"
          SMTP_HOST: 88.198.45.81
          SMTP_PORT: 25
          SMTP_USER: "{{ vault.smtp.user }}"
          SMTP_PASSWORD: "{{ vault.smtp.password }}"
          SMTP_FROM: noreply@simplypool.net
        expose:
          80: 88.198.45.81:8000

      alarm:
        build: alarm
        env:
          POSTGRES_HOST: postgres.main.pool
          POSTGRES_PORT: 5432
          POSTGRES_DB: pool
          POSTGRES_USER: pool
          POSTGRES_PWD: "{{ vault.postgres_users.pool }}"
          SMTP_HOST: 88.198.45.81
          SMTP_PORT: 25
          SMTP_USER: "{{ vault.smtp.user }}"
          SMTP_PASSWORD: "{{ vault.smtp.password }}"
          SMTP_FROM: noreply@simplypool.net
          TELEGRAM_TOKEN: "{{ vault.telegram.token }}"

      telegram_bot:
        build: telegram_bot
        env:
          POSTGRES_HOST: postgres.main.pool
          POSTGRES_PORT: 5432
          POSTGRES_DB: pool
          POSTGRES_USER: pool
          POSTGRES_PWD: "{{ vault.postgres_users.pool }}"
          TELEGRAM_TOKEN: "{{ vault.telegram.token }}"

      frontend:
        build: frontend
        {% if mode == "prod" %}
        docker_file: Dockerfile.prod
        {% endif %}
        env:
          HOSTNAME: 88.198.45.81
          API_URL: http://88.198.45.81:8000
        {% if mode == "dev" %}
        volumes:
          "/usr/src/frontend": "{{ project_dir }}/frontend"
        {% endif %}
        expose:
          {% if mode == "prod" %}
          80: 88.198.45.81:80
          {% else %}
          80: 8080
          {% endif %}

      monero_daemon:
        build: 3rdparty/monero_daemon
        volumes:
          "/root/.bitmonero/": monero_blockchain

      monero_wallet:
        build: 3rdparty/monero_wallet
        volumes:
          "/root/wallet": monero_wallet
        env:
          DAEMON_ADDRESS: monero_daemon.main.pool:18081
          #DAEMON_ADDRESS: testnet.node.xmrlab.com:28081

      ethereum_geth:
        build: 3rdparty/ethereum_geth
        volumes:
          "/root/.ethereum": ethereum_geth
        env:
          EXT_IP: 88.198.45.19
        expose:
          30303: 88.198.45.19:30303

      ethereum_geth_testnet:
        build: 3rdparty/ethereum_geth
        volumes:
          "/root/.ethereum": ethereum_geth_testnet
        env:
          TESTNET: "true"
          EXT_IP: 88.198.45.19
        expose:
          30302: 88.198.45.19:30302

      karbo_daemon:
        build: 3rdparty/karbo_daemon
        volumes:
          "/root/.karbowanec/": karbo_blockchain

      karbo_wallet:
        build: 3rdparty/karbo_wallet
        volumes:
          "/root/wallet": karbo_wallet
        env:
          DAEMON_HOST: karbo_daemon.main.pool
          DAEMON_PORT: 32348
          #DAEMON_ADDRESS: testnet.node.xmrlab.com:28081
